server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: CANDIDATE-SERVICE
          uri: lb://CANDIDATE-SERVICE
          predicates:
            - Path=/candidate/**
        - id: HR-SERVICE
          uri: lb://HR-SERVICE
          predicates:
            - Path=/hr/**
        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/Jobs/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost